### ISSUE TITLE
파일 block개수 비교 기반 기술 조사

### ISSUE THREAD

**Issue by chany0ng** [chany0ng/Project2#4]
int stat(const char *path, struct stat *buf);
파일의 크기, 파일의 권한, 파일의 생성일시, 파일의 최종 변경일 등, 파일의 상태나 파일의 정보를 얻어 오는 함수를 이용한다.

파일의 상태를 stat구조체로 파악할 수 있다.
struct stat{
long st_blocks;//할당한 블록의 개수
};
st_blocks를 이용하여 파일의 할당한 블록의 개수를 알아낼 수 있다.

**Comment by minig0lem** [comment]
ㅎㅇ

**Comment by chany0ng** [comment]
이슈 닫습니다
